### ISSUE TITLE
Publishing recommended feeds

### ISSUE THREAD

**Issue by ralexander-phi** [Dan-Q/well-known-feeds#2]
I'm exploring the idea of publishing "suggested feeds" in a discoverable way. For example, a website owner may wish to promote similar sites, or sites to which they personally subscribe. This use case is a little different than what's described as the feeds belong to different sites and have a different author.

Is this use case something this RFC would support?

As a concrete examples, I'm trying to find a way to publish my feedland feed list (https://feedland.com/opml?screenname=robalexdev) to make it easier for people on my website to discover those feeds. Eventually, it would be nice if RSS user agents could show those suggestions in a social network sort of way.

**Comment by Dan-Q** [comment]
Interesting! I can't see any reason why not. OPML's rich enough that it could easily be used to provide several groups of content, including those both on and off the site, and both "belonging" to and merely "recommended" by the site.

**Comment by Dan-Q** [comment]
@scripting proposes an alternate scheme for publishing a blogroll, BTW, which is more-like what already exists and so more-likely to gain traction. Worth a look: https://opml.org/blogroll.opml

**Comment by ralexander-phi** [comment]
That's exactly what I was looking for. Thank you!

**Comment by ralexander-phi** [comment]
For completeness, I also found `.well-known/recommendations.opml` in use for this purpose:

* https://www.manton.org/.well-known/recommendations.opml
* https://www.google.com/search?hl=en&q=.well%2Dknown%2Frecommendations.opml
